baseURL: 'http://blog.mooy.me/'
title: MooyJiang's Blog
languageCode: zh-tw # 預設語系配置
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

paginate: 15 # 每頁顯示文章數

defaultContentLanguage: zh-tw
defaultContentLanguageInSubdir: false

enableGitInfo: false

frontmatter:
  date:
    - date
    - publishDate
    - lastmod
  expiryDate:
    - expiryDate
  lastmod:
    - :git
    - :fileModTime
    - lastmod
    - date
    - publishDate
  publishDate:
    - publishDate
    - date

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - name: Home
      url: /
      weight: 10
    - name: Archive
      url: archives
      weight: 30
    - name: About Me
      url: about
      weight: 40
    - name: Search
      url: search
      weight: 20

outputs: # For search page
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production
  description: "This is MooyJiang's Blog"
  keywords: [Blog, Portfolio, PaperMod]
  author: MooyJiang
  defaultTheme: dark
  disableThemeToggle: false

  DateFormat: "2006-01-02"
  ShowShareButtons: true
  ShareButtons: ["telegram", "twitter","facebook"]
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowBreadCrumbs: true
  ShowAllPagesInArchive: true
  ShowFullTextinRSS: true
  ShowWordCount: true
  ShowLastMod: true
  ShowRssButtonInSectionTermList: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  displayFullLangName: true
  comments: true
  hidemeta: false
  hideSummary: false
  hideFooter: false # 隱藏頁腳
  VisitCount: true
  UseHugoToc: true
  ShowToc: true
  tocopen: false

  label:
    text: "MooyJiang's Blog"
    icon: "/images/icon.png"
    iconHeight: 35

  # Display thumbnail image of each post on index pages (false: disabled, true: enabled)
  # 文章缩略图功能
  thumbnailImage: true
  # 缩略图位置，我觉得放在上面好看，如果用的小图片作缩略图
  # 可以放在（left或者right），设置此项会取代配置文件中默认在下边的设置
  thumbnailImagePosition: top
  # 这个下边默认就好了，暂时不清楚有什么影响
  autoThumbnailImage: yes
  metaAlignment: left

  # profile-mode
  profileMode:
    enabled: false
    title: "<Title>" # optional default will be site title
    subtitle: "This is subtitle"
    # imageUrl: "<image link>" # optional
    # imageTitle: "<title of image as alt>" # optional
    # imageWidth: 120 # custom size
    # imageHeight: 120 # custom size
    buttons:
      - name: Archive
        url: "/archive"
      - name: About
        url: "/about"

  homeInfoParams: 
    Title: "筆記、見聞"
    Content: >
      小小藥師，愛看電影、聽音樂、打排球。來自高雄，現居台北。<br>
      Born in Kaohsiung, Taiwan in 1994.<br>
      Now a pharmacist working in Taipei.<br>
      Chinese, English, Taiwanese.<br>
      Love music, photopraphy, technology, and volleyball.<br>
      Enjoyer of all interesting and risky things.<br>

  socialIcons:
    - name: telegram
      url: "https://t.me/s/mooyjiang"
    - name: instagram
      url: "http://instagram.com/mooyjiang/"
    - name: twitter
      url: "https://twitter.com/mooyjiang"
    - name: facebook
      url: "https://www.facebook.com/mooy575/"
    - name: github
      url: "https://github.com/mooyjiang"
    - name: Rss
      url: "index.xml"

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

  cover:
    linkFullImages: false
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

markup:
  goldmark:
    renderer:
      unsafe: true # HUGO 默认转义 Markdown 文件中的 HTML 代码，如需开启的话
  highlight: 
    # anchorLineNos: true
    codeFences: true  
    guessSyntax: true
    lineNos: true
    # noClasses: false
    # style: monokai
    style: darcula

      # codeFences：代码围栏功能，这个功能一般都要设为 true 的，不然很难看，就是干巴巴的-代码文字，没有颜色。
      # guessSyntax：猜测语法，这个功能建议设置为 true, 如果你没有设置要显示的语言则会自动匹配。
      # hl_Lines：高亮的行号，一般这个不设置，因为每个代码块我们可能希望让高亮的地方不一样。
      # lineNoStart：行号从编号几开始，一般从 1 开始。
      # lineNos：是否显示行号，我比较喜欢显示，所以我设置的为 true.
      # lineNumbersInTable：使用表来格式化行号和代码,而不是 标签。这个属性一般设置为 true.
      # noClasses：使用 class 标签，而不是内嵌的内联样式

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
